# -*- coding: utf-8 -*-
"""Python_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ksg2C41YpyYU3e-0ungm0GeVFeFbzLi
"""

import pandas as pd
import numpy as np

info=np.array(['P','a','n','d','a','s'])
a=pd.Series(info)
print(a)

# a list of strings
x=['Python','Pandas','C++','Numpy']
#Calling dataframe constructor on list
df=pd.DataFrame(x)
print(df)

a=pd.Series(['Java','C','C++',np.NaN])
a.map({'java':'core'})#map functions
#print(a)
a.map('I like {}'.format,na_action='ignore')

emp=['Ramesh','Kaushal','Amit','Neeraj','Manish']
id=[102,107,109,114,118]
emp_series=pd.Series(emp)
id_series=pd.Series(id)
frame={'Emp':emp_series,'ID':id_series}
result=pd.DataFrame(frame)
print(result)

s=pd.Series(['a','b','h','i','s','h','e','k'])
s.to_frame()
print(s)

df=pd.DataFrame()
print(df)#empty DataFrame

x=['aman','rajat','tejas']
df=pd.DataFrame(x)#Data Frame creation by list
print(df)

info={'ID':[101,102,103,104,105],'Department':['B.Tech','M.tech','Phd','B.A.','B.Sc.']}
df=pd.DataFrame(info)#Data Frame creation by dictionary
print(df)

info={'one':pd.Series([1,2,3,4,5,6,np.NaN],index=['a','b','c','d','e','f','g']),
      'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1=pd.DataFrame(info)#Data Frame creation by dictionary of series
print(d1)

print(d1['one'])

d1['three']=pd.Series([20,40,60],index=['a','b','c'])
print(d1)
print("Adding new column using existing Dataframe column")
d1['four']=d1['one']+d1['three']
print(d1)

info={'one':pd.Series([1,2],index=['a','b']),
      'two':pd.Series([1,2,3],index=['a','b','c'])}
df=pd.DataFrame(info)
print(df)

del df['one']
print(df)

df.pop('two')
print(df)

info={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),
      'two':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])}
df=pd.DataFrame(info)
print(df.iloc[3])

print(df[2:5])

d=pd.DataFrame([[7,8],[9,10]],columns=['x','y'],index=[1,2])
d2=pd.DataFrame([[11,12],[13,14]],columns=['x','y'],index=[3,4])#df=pd.DataFrame(<list>,<columns>)
d=d.append(d2)
print(d)

d.describe()

a_info=pd.DataFrame([[4,5],[6,7]],columns=['x','y'])
b_info=pd.DataFrame([[8,9],[10,11]],columns=['x','y'],index=[2,3])
c_info=pd.DataFrame()
c_info=a_info.append(b_info)
print(c_info)
c_info=c_info.drop(0)
print(c_info)

d.head()

d.hist()

d.mean()

d.melt()

print(df)
df.transpose()

